### ISSUE TITLE
[Android Bootcamp] Project 0: Todo- Ready for Review

### ISSUE THREAD

**Issue by qianwen** [qianwen/android-SimpleTodo#1]
My app is complete, please review. /cc @codepathreview @codepath

Please let me know if I miss any error handling, or other code issue. Also, I have a question about how to add an icon on the ActionBar.

**Comment by nesquena** [comment]
Can you add a GIF walkthrough to the README? Looks like you have a heading for it but I don't see the actual working GIF. Ping me back here when that's added. Thanks.

**Comment by qianwen** [comment]
@nesquen Hi Nathan, sorry for the missing GIF. I didn't add the correct link. The GIF is there now.

**Comment by nesquena** [comment]
Qianwen,

Looks good! This was intended in part to give you an introduction to the general rhythm of this course. The course is entirely project based with an app being assigned each week and then due the following week. Each project builds on the last to help each engineer to learn all practical Android development and best practices as quickly as possible. We also do a personalized code review for each submitted project once the bootcamp starts.

The next step is to continue working on [extensions to your todo app](http://courses.codepath.com/snippets/intro_to_android/prework#heading-5-extending-your-todo) and to **schedule a short 5-10 minute phone conversation** [here](https://www.google.com/calendar/selfsched?sstoken=UURvT01vbzBza1pnfGRlZmF1bHR8NzVjYzBkN2EyZTRiOGRmYjZlZjhmMjA2N2IyMGMwYWU). Navigate to [January 21th and dates onward](https://www.google.com/calendar/selfsched?sstoken=UURvT01vbzBza1pnfGRlZmF1bHR8NzVjYzBkN2EyZTRiOGRmYjZlZjhmMjA2N2IyMGMwYWU) and choose a 15-minute slot. Let us know if none of those times work.

Please make sure to **include the best number** to reach you at in the scheduled event? Look forward to chatting soon!
